---
title: Hello World
author: Ingrid Zoll
date: '2021-03-15'
slug: hello-world
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-15T18:04:42-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: true
---

```{r}
library(tidyverse)
library(leaflet)
library(pdxTrees)
library(forcats)
library(widgetframe)
```


```{r echo=FALSE}
#order: lon, lat, species, date, condition, common name, scientific name, family, collected by

parks<-get_pdxTrees_parks() #full data


smallparks <- parks %>%
  select(1, 2, 8, 7, 10, 9, 17, 5, 15, 6) %>% #select columns, reorder
  mutate(source="park")

streets<-get_pdxTrees_streets() #full data

smallstreets<- streets %>%
  select(22, 23, 3, 2, 5, 18, 15, 16, 14, 4) %>% #select columns, reorder 
  rename("Scientific_Name"="Scientific") %>%
  mutate(source="street")


pdxTrees <- bind_rows(smallparks, smallstreets) #join
```

```{r}
thpl <- pdxTrees %>%
  filter(Species=="THPL") %>%
  filter(!is.na(Collected_By))

thpl$Condition <- factor(thpl$Condition) %>%
  fct_relevel(c("Good", "Fair", "Poor"))

thplgood <- thpl %>%
  filter(Condition =="Good")

thplfair <- thpl %>%
  filter(Condition =="Fair")

thplpoor <- thpl %>%
  filter(Condition =="Poor")
```

```{r}
#create color palette for condition
pal <- colorFactor(c("goldenrod1", "forestgreen", "tomato"), 
                   domain = c("Good", "Fair", "Poor"))

#creating map 1
map1 <- leaflet(data = thpl, options = leafletOptions(minZoom = 10, maxZoom = 21)) %>% 
  setView(lng = -122.6, lat = 45.5, zoom = 11) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addCircleMarkers(lng = ~Longitude, lat = ~Latitude, 
             popup=paste("Collected by:", thpl$Collected_By, "<br>",
                           "Date:", thpl$Inventory_Date, "<br>",
                           "DBH:", thpl$DBH), 
             color=~pal(Condition), 
             clusterOptions = markerClusterOptions(disableClusteringAtZoom=14), 
             stroke = TRUE, fillOpacity = 0.7, radius = 3) %>%
  addLegend("bottomright", pal = pal, 
            values= ~Condition,
            title = "Condition",
            opacity = 1)

frameWidget(map1, width = "100%")

htmlwidgets::saveWidget(frameWidget(map1, width = "100%"), file = "map1.html", selfcontained = TRUE)
```

<iframe src="content/post/2021-03-15-hi-hugo/map1/index.html"></iframe>

